# Generated by Django 5.0.1 on 2024-01-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.RenameField(
            model_name='amenity',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='amenity',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='', max_length=180),
        ),
    ]
